### ISSUE TITLE
Can i add a tower of hanoi code

### ISSUE THREAD

**Issue by Priyanshu-rajput-01** [KhyatiSaini/Hacktoberfest#4]
I want to contribute to this repository by adding a tower of hanoi code in c++ language

**Comment by Priyanshu-rajput-01** [comment]
@KhyatiSaini please accept my request

**Comment by KhyatiSaini** [comment]
> @KhyatiSaini please accept my request

Yes go ahead

**Comment by Priyanshu-rajput-01** [comment]
> @KhyatiSaini please accept my request



> > @KhyatiSaini please accept my request
> 
> Yes go ahead

i have added the code please preview it and accept my pull request
